# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scoring.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'scoring.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rscoring.proto\x12\x07scoring\"\xdb\x01\n\x0eStrokeFeatures\x12\x0e\n\x06gender\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x01\x12\x14\n\x0chypertension\x18\x03 \x01(\x05\x12\x15\n\rheart_disease\x18\x04 \x01(\x05\x12\x14\n\x0c\x65ver_married\x18\x05 \x01(\t\x12\x11\n\twork_type\x18\x06 \x01(\t\x12\x16\n\x0eresidence_type\x18\x07 \x01(\t\x12\x19\n\x11\x61vg_glucose_level\x18\x08 \x01(\x01\x12\x0b\n\x03\x62mi\x18\t \x01(\x01\x12\x16\n\x0esmoking_status\x18\n \x01(\t\"5\n\x0bStrokeBatch\x12&\n\x05items\x18\x01 \x03(\x0b\x32\x17.scoring.StrokeFeatures\"u\n\nPrediction\x12\x18\n\x10stroke_predicted\x18\x01 \x01(\x08\x12\r\n\x05label\x18\x02 \x01(\t\x12\x13\n\x0bprobability\x18\x03 \x01(\x01\x12\x12\n\nmodel_name\x18\x04 \x01(\t\x12\x15\n\rmodel_version\x18\x05 \x01(\x05\x32\x7f\n\x07Scoring\x12\x37\n\x07Predict\x12\x17.scoring.StrokeFeatures\x1a\x13.scoring.Prediction\x12;\n\x0cPredictBatch\x12\x14.scoring.StrokeBatch\x1a\x13.scoring.Prediction0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scoring_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STROKEFEATURES']._serialized_start=27
  _globals['_STROKEFEATURES']._serialized_end=246
  _globals['_STROKEBATCH']._serialized_start=248
  _globals['_STROKEBATCH']._serialized_end=301
  _globals['_PREDICTION']._serialized_start=303
  _globals['_PREDICTION']._serialized_end=420
  _globals['_SCORING']._serialized_start=422
  _globals['_SCORING']._serialized_end=549
# @@protoc_insertion_point(module_scope)
